sonar.projectKey=golo-ads-service
sonar.projectName=GOLO Backend - ADS Service
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,*.js

sonar.typescript.tsconfigPath=tsconfig.json
sonar.typescript.eslint.enabled=true
sonar.typescript.eslint.reportPaths=reports/eslint-report.json

sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,src/main.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
